import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useThemeStore } from '../../src/store/theme';
import { api } from '../../src/api/client';
import type { Client } from '../../src/types';

const money = (v: any) => `\u20A6${Number(v || 0).toLocaleString('en-NG', { maximumFractionDigits: 0 })}`;
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const parseDate = (v: string) => { const [y,m,d]=v.split('-').map(Number); const x=new Date(); x.setHours(12,0,0,0); if(y&&m&&d)x.setFullYear(y,m-1,d); return x; };
const formatDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const num = (v:any) => { const n=Number(v); return Number.isFinite(n)?n:0; };

type Settings = { max_installments_per_payment:number; min_installments_per_payment:number; min_savings_amount:number; max_savings_amount:number; allow_weekend_collection:number; date_readonly:number };
type Loan = { total_payable:number; remaining_balance:number; principal:number; inst_amt:number; installments_paid:number; num_installments:number };
type Row = Client & { savings_balance:number; loan:Loan|null; existing:{loan_amt:number;sav_amt:number;wth_type:string;wth_amt:number} };
type Edit = { installments:string; savings:string; adjustment:string; adjustmentAmount:string };
const defaults:Settings={max_installments_per_payment:2,min_installments_per_payment:1,min_savings_amount:100,max_savings_amount:500000,allow_weekend_collection:0,date_readonly:0};

export default function CombinedCollectionScreen(){
 const colors=useThemeStore(s=>s.colors); const [date,setDate]=useState(today()); const [showDate,setShowDate]=useState(false); const [clients,setClients]=useState<Client[]>([]); const [unions,setUnions]=useState<string[]>([]); const [activeUnion,setActiveUnion]=useState(''); const [rows,setRows]=useState<Row[]>([]); const [edits,setEdits]=useState<Record<string,Edit>>({}); const [settings,setSettings]=useState(defaults); const [loading,setLoading]=useState(true); const [loadingRows,setLoadingRows]=useState(false); const [saving,setSaving]=useState<string|null>(null); const [refreshing,setRefreshing]=useState(false);
 const loadUnions=useCallback(async()=>{setLoading(true);try{const active=await api.getAllClients();setClients(active);const names=Array.from(new Set(active.map((c:any)=>c.union===null||c.union===undefined||c.union===''?'Unassigned':String(c.union)))).sort((a,b)=>a.localeCompare(b));setUnions(names);setActiveUnion(p=>p&&names.includes(p)?p:(names[0]||''));}catch(e:any){Alert.alert('Unable to load clients',e?.message||'Please try again.');}finally{setLoading(false);}},[]);
 const loadUnion=useCallback(async()=>{if(!activeUnion){setRows([]);return;}setLoadingRows(true);try{const unionParam=activeUnion==='Unassigned'?'':activeUnion;const combined=await api.getCombinedUnionData(unionParam,date);const st=(combined as any).__settings;if(st){setSettings(p=>({...p,...(st.collection||{}),...(st.savings||{}),date_readonly:st.date_readonly?1:0}));}const byId=new Map<string,any>();(Array.isArray(combined)?combined:[]).forEach((x:any)=>byId.set(String(x.id),x));const loaded=clients.filter(c=>(String(c.union||'').trim()||'Unassigned')===activeUnion).map(c=>{const x=byId.get(String(c.id))||{};const l=x.loan;const loan=l?{...l,total_payable:num(l.total_payable),remaining_balance:num(l.remaining_balance),principal:num(l.principal),inst_amt:num(l.inst_amt),installments_paid:num(l.installments_paid),num_installments:num(l.num_installments)}:null;return {...c,savings_balance:num(x.savings_balance),loan,existing:x.existing||{loan_amt:0,sav_amt:0,wth_type:'',wth_amt:0}} as Row;}).sort((a,b)=>a.name.localeCompare(b.name));setRows(loaded);const next:Record<string,Edit>={};loaded.forEach(r=>{const i=r.loan?.inst_amt||0;const old=r.existing.loan_amt||0;next[r.id]={installments:i&&old?String(Math.min(2,Math.max(1,Math.round(old/i)))):'',savings:r.existing.sav_amt?String(r.existing.sav_amt):'',adjustment:r.existing.wth_type||'',adjustmentAmount:r.existing.wth_amt?String(r.existing.wth_amt):''};});setEdits(next);}catch(e:any){Alert.alert('Unable to load collection data',e?.message||'Please try again.');setRows([]);}finally{setLoadingRows(false);}},[activeUnion,clients,date]);
 useFocusEffect(useCallback(()=>{loadUnions();},[loadUnions])); useEffect(()=>{loadUnion();},[loadUnion]);
 const refresh=async()=>{setRefreshing(true);await loadUnions();setRefreshing(false);};
 const setEdit=(id:string,key:keyof Edit,value:string)=>setEdits(p=>({...p,[id]:{...p[id], [key]:value}}));
 const locked=Number(settings.date_readonly)===1;
 const save=async(row:Row)=>{const e=edits[row.id]||{installments:'',savings:'',adjustment:'',adjustmentAmount:''};const installments=Math.max(0,parseInt(e.installments||'0',10)||0);const savings=num(String(e.savings).replace(/,/g,''));const adjustmentAmount=num(String(e.adjustmentAmount).replace(/,/g,''));if(installments>settings.max_installments_per_payment){Alert.alert('Installment limit',`Maximum allowed is ${settings.max_installments_per_payment} installment(s).`);return;}if(installments>0&&e.adjustment){Alert.alert('Invalid collection','Repayment and Deduct/Return cannot be processed together.');return;}if(installments>=2&&e.adjustment){Alert.alert('Invalid collection','Deduct/Return is not allowed when repaying 2 installments.');return;}if(savings>0&&(savings<settings.min_savings_amount||savings>settings.max_savings_amount)){Alert.alert('Savings limit',`Savings must be between ${money(settings.min_savings_amount)} and ${money(settings.max_savings_amount)}.`);return;}if(!installments&&!savings&&!adjustmentAmount){Alert.alert('Nothing to save','Enter an installment, savings amount, or adjustment.');return;}setSaving(row.id);try{const res=await api.saveCombinedCollection({client_id:row.id,date,installment:installments,savings_amount:savings,withdrawal_type:e.adjustment,withdrawal_amount:adjustmentAmount});if(!res?.success)throw new Error(res?.error||res?.message||'Unable to save collection.');Alert.alert('Collection saved',res.message||`${row.name} collection saved successfully.`);await loadUnion();}catch(err:any){Alert.alert('Collection failed',err?.message||'Unable to save collection.');}finally{setSaving(null);}};
 const totalSavings=rows.reduce((s,r)=>s+r.savings_balance,0); const totalLoan=rows.reduce((s,r)=>s+(r.loan?.remaining_balance||0),0);
 return <KeyboardAvoidingView style={{flex:1,backgroundColor:colors.background}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={{flex:1}} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary}/>}> 
  <View style={styles.header}><View><Text style={[styles.title,{color:colors.text}]}>Combined Collection</Text><Text style={[styles.subtitle,{color:colors.textSecondary}]}>Savings and loan collection register</Text></View><View style={[styles.badge,{backgroundColor:colors.infoBg}]}><Text style={[styles.badgeText,{color:colors.primary}]}>COMBINED</Text></View></View>
  <View style={[styles.summary,{backgroundColor:colors.card,borderColor:colors.border}]}><Summary label="CLIENTS" value={rows.length} colors={colors}/><View style={[styles.divider,{backgroundColor:colors.border}]}/><Summary label="SAVINGS" value={money(totalSavings)} colors={colors}/><View style={[styles.divider,{backgroundColor:colors.border}]}/><Summary label="LOAN BALANCE" value={money(totalLoan)} colors={colors}/></View>
  <Pressable onPress={()=>!locked&&setShowDate(true)} style={[styles.dateBox,{backgroundColor:colors.card,borderColor:colors.border}]}><Ionicons name={locked?'lock-closed':'calendar-outline'} size={18} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.label,{color:colors.textMuted}]}>COLLECTION DATE{locked?' • LOCKED':''}</Text><Text style={[styles.date,{color:colors.text}]}>{date}</Text></View><Ionicons name="chevron-forward" size={16} color={colors.textMuted}/></Pressable>
  {showDate?<DateTimePicker value={parseDate(date)} mode="date" display={Platform.OS==='ios'?'spinner':'calendar'} onChange={(ev,d)=>{if(ev.type==='set'&&d)setDate(formatDate(d));if(Platform.OS!=='ios'||ev.type==='dismissed')setShowDate(false);}}/>:null}
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{unions.map(u=>{const active=u===activeUnion;const count=clients.filter(c=>(String(c.union||'').trim()||'Unassigned')===u).length;return <Pressable key={u} onPress={()=>setActiveUnion(u)} style={[styles.tab,{backgroundColor:active?colors.primary:colors.card,borderColor:active?colors.primary:colors.border}]}><Text style={[styles.tabText,{color:active?'#fff':colors.text}]}>{u}</Text><Text style={[styles.count,{color:active?'#fff':colors.primary}]}>{count}</Text></Pressable>})}</ScrollView>
  {loading||loadingRows?<View style={styles.loading}><ActivityIndicator size="large" color={colors.primary}/><Text style={[styles.loadingText,{color:colors.textSecondary}]}>Loading clients...</Text></View>:rows.length===0?<View style={[styles.empty,{backgroundColor:colors.card,borderColor:colors.border}]}><Ionicons name="people-outline" size={38} color={colors.textMuted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>No clients in this union</Text></View>:rows.map(row=>{const e=edits[row.id]||{installments:'',savings:'',adjustment:'',adjustmentAmount:''};const loan=row.loan;const total=num(loan?.total_payable);const outstanding=num(loan?.remaining_balance);const inst=num(loan?.inst_amt);const paid=num(loan?.installments_paid);return <View key={row.id} style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}>
   <View style={styles.client}><View style={[styles.avatar,{backgroundColor:colors.infoBg}]}><Text style={[styles.avatarText,{color:colors.primary}]}>{row.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}</Text></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{row.name}</Text><Text style={[styles.phone,{color:colors.textSecondary}]}>{row.phone||row.id}</Text></View></View>
   <View style={styles.stats}><Stat label="SAVINGS BALANCE" value={money(row.savings_balance)} colors={colors}/><Stat label="LOAN TOTAL" value={money(total)} colors={colors}/><Stat label="OUTSTANDING" value={money(outstanding)} colors={colors}/><Stat label="INSTALLMENT" value={money(inst)} colors={colors}/></View>
   {loan?<View style={[styles.loanInfo,{backgroundColor:colors.infoBg}]}><Text style={[styles.small,{color:colors.textSecondary}]}>LOAN REPAYMENT</Text><Text style={[styles.repay,{color:colors.text}]}>{paid} paid • {money(inst)} per installment</Text></View>:<Text style={[styles.noLoan,{color:colors.textMuted}]}>No Loan</Text>}
   <Text style={[styles.section,{color:colors.text}]}>LOAN REPAYMENT</Text><View style={styles.optionRow}>{[1,2].map(n=><Pressable key={n} disabled={!loan||saving===row.id} onPress={()=>setEdit(row.id,'installments',e.installments===String(n)?'':String(n))} style={[styles.option,{borderColor:e.installments===String(n)?colors.primary:colors.border,backgroundColor:e.installments===String(n)?colors.infoBg:colors.inputBg}]}><Text style={[styles.optionText,{color:e.installments===String(n)?colors.primary:colors.text}]}>{n} × {money(inst)}</Text></Pressable>)}</View>
   <Text style={[styles.section,{color:colors.text}]}>SAVINGS COLLECTION</Text><View style={[styles.inputBox,{borderColor:colors.inputBorder,backgroundColor:colors.inputBg}]}><Text style={[styles.currency,{color:colors.primary}]}>₦</Text><TextInput value={e.savings} onChangeText={v=>setEdit(row.id,'savings',v)} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.textMuted} style={[styles.input,{color:colors.text}]}/></View>
   <Text style={[styles.section,{color:colors.text}]}>ADJUSTMENT</Text><View style={styles.optionRow}>{['Deduct','Return'].map(t=><Pressable key={t} disabled={saving===row.id} onPress={()=>setEdit(row.id,'adjustment',e.adjustment===t?'':t)} style={[styles.option,{borderColor:e.adjustment===t?colors.primary:colors.border,backgroundColor:e.adjustment===t?colors.infoBg:colors.inputBg}]}><Text style={[styles.optionText,{color:e.adjustment===t?colors.primary:colors.text}]}>{t}</Text></Pressable>)}</View>{e.adjustment?<View style={[styles.inputBox,{borderColor:colors.inputBorder,backgroundColor:colors.inputBg}]}><Text style={[styles.currency,{color:colors.primary}]}>₦</Text><TextInput value={e.adjustmentAmount} onChangeText={v=>setEdit(row.id,'adjustmentAmount',v)} keyboardType="decimal-pad" placeholder="Amount" placeholderTextColor={colors.textMuted} style={[styles.input,{color:colors.text}]}/></View>:null}
   <Pressable disabled={saving===row.id} onPress={()=>save(row)} style={[styles.save,{backgroundColor:colors.primary,opacity:saving===row.id?.65:1}]}>{saving===row.id?<ActivityIndicator color="#fff"/>:<><Ionicons name="checkmark-circle-outline" size={19} color="#fff"/><Text style={styles.saveText}>SAVE COLLECTION</Text></>}</Pressable>
  </View>})}
 </ScrollView></KeyboardAvoidingView>;
}
function Summary({label,value,colors}:any){return <View style={styles.summaryItem}><Text style={[styles.label,{color:colors.textMuted}]}>{label}</Text><Text style={[styles.summaryValue,{color:colors.text}]}>{value}</Text></View>}
function Stat({label,value,colors}:any){return <View style={[styles.stat,{backgroundColor:colors.inputBg,borderColor:colors.border}]}><Text style={[styles.label,{color:colors.textMuted}]}>{label}</Text><Text style={[styles.statValue,{color:colors.text}]}>{value}</Text></View>}
const styles=StyleSheet.create({content:{padding:14,paddingBottom:40},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},title:{fontSize:20,fontWeight:'900'},subtitle:{fontSize:12,marginTop:2},badge:{paddingHorizontal:10,paddingVertical:6,borderRadius:14},badgeText:{fontSize:10,fontWeight:'900'},summary:{borderWidth:1,borderRadius:16,padding:12,flexDirection:'row',alignItems:'center',marginBottom:10},summaryItem:{flex:1,alignItems:'center'},label:{fontSize:9,fontWeight:'800'},summaryValue:{fontSize:13,fontWeight:'900',marginTop:3},divider:{width:1,height:32},dateBox:{borderWidth:1,borderRadius:14,padding:12,flexDirection:'row',alignItems:'center',gap:10,marginBottom:10},date:{fontSize:16,fontWeight:'900',marginTop:2},tabs:{gap:8,paddingBottom:10},tab:{borderWidth:1,borderRadius:18,paddingHorizontal:12,paddingVertical:8,flexDirection:'row',alignItems:'center',gap:7},tabText:{fontSize:12,fontWeight:'800'},count:{fontSize:11,fontWeight:'900'},loading:{paddingVertical:50,alignItems:'center',gap:10},loadingText:{fontSize:13},empty:{borderWidth:1,borderRadius:16,padding:30,alignItems:'center',marginTop:10},emptyTitle:{fontSize:15,fontWeight:'800',marginTop:8},card:{borderWidth:1,borderRadius:18,padding:13,marginBottom:12},client:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:14,fontWeight:'900'},name:{fontSize:15,fontWeight:'900'},phone:{fontSize:11,marginTop:2},stats:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},stat:{width:'48%',borderWidth:1,borderRadius:10,padding:9},statValue:{fontSize:14,fontWeight:'900',marginTop:3},loanInfo:{borderRadius:10,padding:9,marginTop:8},small:{fontSize:9,fontWeight:'800'},repay:{fontSize:12,fontWeight:'800',marginTop:2},noLoan:{fontSize:11,fontWeight:'800',marginTop:10},section:{fontSize:11,fontWeight:'900',marginTop:13,marginBottom:6},optionRow:{flexDirection:'row',gap:8},option:{flex:1,borderWidth:1,borderRadius:10,paddingVertical:10,alignItems:'center'},optionText:{fontSize:12,fontWeight:'800'},inputBox:{borderWidth:1,borderRadius:10,minHeight:44,flexDirection:'row',alignItems:'center',paddingHorizontal:10},currency:{fontSize:16,fontWeight:'900'},input:{flex:1,fontSize:15,fontWeight:'800',paddingVertical:8,paddingHorizontal:7},save:{marginTop:14,minHeight:45,borderRadius:11,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},saveText:{color:'#fff',fontSize:12,fontWeight:'900'}});
