import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useThemeStore } from '../../src/store/theme';
import { api } from '../../src/api/client';
import type { Client } from '../../src/types';

const money=(v:any)=>`₦${Number(v||0).toLocaleString('en-NG',{maximumFractionDigits:0})}`;
const num=(v:any)=>Number(String(v??'').replace(/,/g,''))||0;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const parseDate=(v:string)=>{const [y,m,d]=v.split('-').map(Number);const x=new Date();x.setHours(12,0,0,0);if(y&&m&&d)x.setFullYear(y,m-1,d);return x};
const formatDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const unionOf=(c:Client)=>String(c.union??'').trim()||'Unassigned';

type Row=Client&{loan:any;savings_balance:number;existing:any};
type Edit={savings:string;installments:string;withdrawalType:''|'cash'|'withdrawal'|'return';withdrawal:string};
type Settings={max_installments_per_payment:number;min_installments_per_payment:number;min_savings_amount:number;max_savings_amount:number;allow_weekend_collection:number;max_cash_withdrawal:number;allow_weekend_withdrawals:number;blocked_withdrawal_types:string|string[];buffer_cash:number;buffer_withdrawal:number;buffer_return:number;date_readonly:number};
const defaults:Settings={max_installments_per_payment:3,min_installments_per_payment:1,min_savings_amount:100,max_savings_amount:500000,allow_weekend_collection:0,max_cash_withdrawal:50000,allow_weekend_withdrawals:0,blocked_withdrawal_types:'[]',buffer_cash:10,buffer_withdrawal:10,buffer_return:10,date_readonly:0};
const blank=():Edit=>({savings:'',installments:'',withdrawalType:'',withdrawal:''});

export default function CombinedCollectionScreen(){
 const colors=useThemeStore(s=>s.colors);const [date,setDate]=useState(today());const [picker,setPicker]=useState(false);const [clients,setClients]=useState<Client[]>([]);const [unions,setUnions]=useState<string[]>([]);const [activeUnion,setActiveUnion]=useState('');const [rows,setRows]=useState<Row[]>([]);const [edits,setEdits]=useState<Record<string,Edit>>({});const [settings,setSettings]=useState(defaults);const [loading,setLoading]=useState(true);const [loadingRows,setLoadingRows]=useState(false);const [saving,setSaving]=useState<string|null>(null);const [refreshing,setRefreshing]=useState(false);
 const locked=Number(settings.date_readonly)===1||String(settings.date_readonly).toLowerCase()==='true';
 const loadClients=useCallback(async()=>{setLoading(true);try{const data=await api.getAllClients();setClients(data);const u=Array.from(new Set(data.map(unionOf))).sort();setUnions(u);setActiveUnion(p=>p&&u.includes(p)?p:(u[0]||''));}catch(e:any){Alert.alert('Unable to load clients',e?.message||'Please try again.')}finally{setLoading(false)}},[]);
 const loadRows=useCallback(async()=>{if(!activeUnion){setRows([]);return}setLoadingRows(true);try{const result:any=await api.getCombinedUnionData(activeUnion==='Unassigned'?'':activeUnion,date);const meta=result?.__settings;if(meta)setSettings(s=>({...s,...(meta.collection||{}),...(meta.savings||{}),...(meta.withdrawal||{}),date_readonly:meta.date_readonly?1:0}));const list=Array.isArray(result)?result:[];const byId=new Map(list.map((x:any)=>[String(x.id),x]));const rendered=clients.filter(c=>unionOf(c)===activeUnion).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>{const x=byId.get(String(c.id))||{};return {...c,loan:x.loan??null,savings_balance:num(x.savings_balance),existing:x.existing||{loan_amt:0,sav_amt:0,wth_type:'',wth_amt:0}} as Row});setRows(rendered);setEdits(old=>{const n={...old};for(const r of rendered){if(n[r.id])continue;const i=num(r.loan?.inst_amt);const oldLoan=num(r.existing?.loan_amt);n[r.id]={savings:num(r.existing?.sav_amt)?String(r.existing.sav_amt):'',installments:i&&oldLoan?String(Math.round(oldLoan/i)):'',withdrawalType:r.existing?.wth_type||'',withdrawal:num(r.existing?.wth_amt)?String(r.existing.wth_amt):''};}return n});}catch(e:any){Alert.alert('Unable to load collection data',e?.message||'Please try again.');setRows([])}finally{setLoadingRows(false)}},[activeUnion,clients,date]);
 useFocusEffect(useCallback(()=>{loadClients()},[loadClients]));useEffect(()=>{loadRows()},[loadRows]);const refresh=async()=>{setRefreshing(true);await loadClients();setRefreshing(false)};const edit=(id:string,key:keyof Edit,value:string)=>setEdits(p=>({...p,[id]:{...(p[id]||blank()),[key]:value}}));
 const installment=(r:Row)=>num(r.loan?.inst_amt);const remaining=(r:Row)=>num(r.loan?.remaining_balance);const loanTotal=(r:Row)=>num(r.loan?.total_payable);const principal=(r:Row)=>num(r.loan?.principal);const paidInst=(r:Row)=>num(r.loan?.installments_paid);const maxInst=(r:Row)=>Math.max(0,Math.min(num(settings.max_installments_per_payment)||3,installment(r)>0?Math.ceil(remaining(r)/installment(r)):0));
 const blocked=()=>{try{const x=Array.isArray(settings.blocked_withdrawal_types)?settings.blocked_withdrawal_types:JSON.parse(String(settings.blocked_withdrawal_types||'[]'));return x.map((v:any)=>String(v).toLowerCase())}catch{return[]}};
 const adjustment=(r:Row,type:'cash'|'withdrawal'|'return')=>{if(blocked().includes(type))return{disabled:true,text:'Blocked'};if(!r.loan)return{disabled:true,text:'No Loan'};if((type==='cash'||type==='withdrawal')&&paidInst(r)<10)return{disabled:true,text:'< 10 Paid'};const pct=num(type==='cash'?settings.buffer_cash:type==='withdrawal'?settings.buffer_withdrawal:settings.buffer_return)||10;if(num(r.savings_balance)<principal(r)*pct/100)return{disabled:true,text:'Low Savings'};return{disabled:false,text:type==='withdrawal'?'Deduct':type[0].toUpperCase()+type.slice(1)}};
 const chooseAdjustment=(r:Row,type:Edit['withdrawalType'])=>{if(!type){edit(r.id,'withdrawalType','');edit(r.id,'withdrawal','');return}const a=adjustment(r,type);if(a.disabled){Alert.alert('Adjustment unavailable',a.text);return}const current=edits[r.id]||blank();let amount='';if(type==='withdrawal')amount=installment(r)>0?String(Math.round(installment(r))):'';if(type==='return')amount=String(Math.round(Math.min(num(r.savings_balance)+num(current.savings),remaining(r))));edit(r.id,'withdrawalType',type);edit(r.id,'withdrawal',amount);if(type!=='cash')edit(r.id,'installments','');};
 const save=async(r:Row)=>{const e=edits[r.id]||blank();const count=Math.floor(num(e.installments));const sav=num(e.savings);const adj=num(e.withdrawal);const type=e.withdrawalType;const i=installment(r);if(!count&&!sav&&!adj)return Alert.alert('No collection','Enter a loan, savings, Deduct, Return or Cash amount.');if(count>maxInst(r))return Alert.alert('Installment limit',`Maximum: ${maxInst(r)} installments.`);if(count&&type)return Alert.alert('Invalid combination','Loan repayment cannot be combined with Deduct or Return.');if(count&&!i)return Alert.alert('No active loan','This client has no installment amount.');if(sav&&(sav<num(settings.min_savings_amount)||sav>num(settings.max_savings_amount)))return Alert.alert('Savings limit',`Savings must be between ${money(settings.min_savings_amount)} and ${money(settings.max_savings_amount)}.`);if(type==='cash'&&adj>num(settings.max_cash_withdrawal))return Alert.alert('Cash limit','Cash withdrawal exceeds the configured limit.');if((type==='withdrawal'||type==='return')&&adj<=0)return Alert.alert('Invalid adjustment','No valid adjustment amount is available.');if(type&&blocked().includes(type))return Alert.alert('Adjustment disabled','This adjustment is disabled.');const day=parseDate(date).getDay();if((day===0||day===6)&&(count||sav)&&!num(settings.allow_weekend_collection))return Alert.alert('Weekend collection disabled','Weekend collections are disabled.');if((day===0||day===6)&&adj&&!num(settings.allow_weekend_withdrawals))return Alert.alert('Weekend withdrawal disabled','Weekend withdrawals are disabled.');setSaving(r.id);try{const res=await api.saveCombinedCollection({client_id:r.id,date,installment:count,savings_amount:sav,withdrawal_type:type,withdrawal_amount:adj});if(!res?.success)throw new Error(res?.error||res?.message||'Unable to save.');Alert.alert('Saved',res.message||`${r.name} saved successfully.`);await loadRows();}catch(e:any){Alert.alert('Save failed',e?.message||'Unable to save.')}finally{setSaving(null)}};
 const totalSav=rows.reduce((s,r)=>s+num(r.savings_balance),0),totalLoan=rows.reduce((s,r)=>s+remaining(r),0);
 return <KeyboardAvoidingView style={{flex:1,backgroundColor:colors.background}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}> 
  <View style={styles.header}><View><Text style={[styles.title,{color:colors.text}]}>Combined Collection</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>Loan, savings, Deduct and Return</Text></View><View style={[styles.badge,{backgroundColor:colors.infoBg}]}><Text style={{color:colors.primary,fontWeight:'800'}}>COMBINED</Text></View></View>
  <View style={[styles.summary,{backgroundColor:colors.card,borderColor:colors.border}]}><Stat label="CLIENTS" value={rows.length}/><Stat label="SAVINGS" value={money(totalSav)}/><Stat label="LOAN BALANCE" value={money(totalLoan)}/></View>
  <Pressable disabled={locked} onPress={()=>setPicker(true)} style={[styles.date,{backgroundColor:colors.card,borderColor:colors.border,opacity:locked?.6:1}]}><Ionicons name="calendar-outline" size={20} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.label,{color:colors.textMuted}]}>COLLECTION DATE</Text><Text style={[styles.dateText,{color:colors.text}]}>{date}</Text></View><Ionicons name={locked?'lock-closed':'chevron-forward'} size={18} color={colors.textMuted}/></Pressable>
  {picker&&!locked?<DateTimePicker value={parseDate(date)} mode="date" onChange={(e,d)=>{if(e.type==='set'&&d)setDate(formatDate(d));if(Platform.OS!=='ios')setPicker(false)}}/>:null}
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{unions.map(u=>{const on=u===activeUnion;return <Pressable key={u} onPress={()=>setActiveUnion(u)} style={[styles.tab,{backgroundColor:on?colors.primary:colors.card,borderColor:on?colors.primary:colors.border}]}><Text style={{color:on?'#fff':colors.text,fontWeight:'700'}}>{u}</Text><Text style={{color:on?'#fff':colors.primary}}> {clients.filter(c=>unionOf(c)===u).length}</Text></Pressable>})}</ScrollView>
  {loading||loadingRows?<View style={styles.center}><ActivityIndicator size="large" color={colors.primary}/><Text style={{color:colors.textSecondary}}>Loading...</Text></View>:rows.map(r=>{const e=edits[r.id]||blank();const i=installment(r);const max=maxInst(r);const ret=adjustment(r,'return'),ded=adjustment(r,'withdrawal'),cash=adjustment(r,'cash');const returnAmt=Math.min(num(r.savings_balance)+num(e.savings),remaining(r));return <View key={r.id} style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}>
   <View style={styles.client}><View style={[styles.avatar,{backgroundColor:colors.infoBg}]}><Text style={{color:colors.primary,fontWeight:'900'}}>{r.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}</Text></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{r.name}</Text><Text style={{color:colors.textSecondary}}>{r.phone||r.id}</Text></View></View>
   <View style={styles.moneyGrid}><Info title="SAVINGS BALANCE" value={money(r.savings_balance)}/><Info title="LOAN TOTAL" value={money(loanTotal(r))}/><Info title="OUTSTANDING" value={money(remaining(r))}/><Info title="INSTALLMENT" value={money(i)}/></View>
   {r.loan?<View style={[styles.loanBox,{backgroundColor:colors.background}]}><Text style={{color:colors.text,fontWeight:'800'}}>Loan: {money(loanTotal(r))} • Outstanding: {money(remaining(r))}</Text><Text style={{color:colors.primary,fontWeight:'800'}}>1 installment = {money(i)} • Paid: {paidInst(r)}</Text></View>:null}
   <Text style={[styles.section,{color:colors.text}]}>LOAN REPAYMENT</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{Array.from({length:max},(_,idx)=>idx+1).map(n=>{const selected=num(e.installments)===n;return <Pressable key={n} disabled={!!e.withdrawalType||!i} onPress={()=>edit(r.id,'installments',selected?'':String(n))} style={[styles.option,{backgroundColor:selected?colors.primary:colors.background,borderColor:selected?colors.primary:colors.border}]}><Text style={{color:selected?'#fff':colors.text,fontWeight:'800'}}>{n} • {money(i*n)}</Text></Pressable>})}</ScrollView>
   <Text style={[styles.section,{color:colors.text}]}>SAVINGS COLLECTION</Text><TextInput value={e.savings} onChangeText={v=>edit(r.id,'savings',v)} keyboardType="numeric" placeholder="Enter savings amount" placeholderTextColor={colors.textMuted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.background}]}/>
   <Text style={[styles.section,{color:colors.text}]}>ADJUSTMENT</Text><View style={styles.adjustRow}>{[['withdrawal',ded],['return',ret],['cash',cash]].map(([type,a]:any)=><Pressable key={type} disabled={a.disabled} onPress={()=>chooseAdjustment(r,type)} style={[styles.adjust,{backgroundColor:e.withdrawalType===type?colors.primary:colors.background,borderColor:a.disabled?colors.border:colors.primary,opacity:a.disabled?.45:1}]}><Text style={{color:e.withdrawalType===type?'#fff':colors.text,fontWeight:'800'}}>{a.text}</Text></Pressable>)}</View>
   {e.withdrawalType?<View style={[styles.adjustInfo,{backgroundColor:colors.infoBg}]}><Text style={{color:colors.primary,fontWeight:'800'}}>{e.withdrawalType==='withdrawal'?'Deduct amount':e.withdrawalType==='return'?'Return amount':'Cash amount'}: {money(e.withdrawal)}</Text>{e.withdrawalType==='return'?<Text style={{color:colors.primary}}>Max Return: {money(returnAmt)}</Text>:null}</View>:null}
   <Pressable disabled={saving===r.id} onPress={()=>save(r)} style={[styles.save,{backgroundColor:colors.primary,opacity:saving===r.id?.6:1}]}>{saving===r.id?<ActivityIndicator color="#fff"/>:<><Ionicons name="checkmark-circle-outline" size={20} color="#fff"/><Text style={styles.saveText}>SAVE COLLECTION</Text></>}</Pressable>
  </View>})}
 </ScrollView></KeyboardAvoidingView>;
}
function Stat({label,value}:{label:string;value:any}){return <View style={{flex:1,alignItems:'center'}}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>}
function Info({title,value}:{title:string;value:string}){return <View style={styles.info}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({content:{padding:16,paddingBottom:40,gap:12},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:24,fontWeight:'900'},sub:{marginTop:3},badge:{paddingHorizontal:10,paddingVertical:7,borderRadius:10},summary:{flexDirection:'row',padding:14,borderWidth:1,borderRadius:14},statLabel:{fontSize:10,fontWeight:'800',color:'#777'},statValue:{fontSize:16,fontWeight:'900',marginTop:4},date:{borderWidth:1,borderRadius:14,padding:13,flexDirection:'row',alignItems:'center',gap:12},label:{fontSize:10,fontWeight:'800'},dateText:{fontSize:16,fontWeight:'800',marginTop:2},tabs:{gap:8,paddingVertical:2},tab:{paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderRadius:20,flexDirection:'row',gap:4},center:{padding:40,alignItems:'center',gap:10},card:{borderWidth:1,borderRadius:18,padding:14,gap:10},client:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'900'},moneyGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},info:{width:'47%',padding:10,borderRadius:10,backgroundColor:'rgba(128,128,128,.08)'},infoTitle:{fontSize:9,fontWeight:'800',color:'#777'},infoValue:{fontSize:15,fontWeight:'900',marginTop:3},loanBox:{padding:10,borderRadius:10,gap:4},section:{fontSize:11,fontWeight:'900',marginTop:3},option:{paddingHorizontal:12,paddingVertical:10,borderRadius:10,borderWidth:1},input:{borderWidth:1,borderRadius:10,padding:11,fontSize:15},adjustRow:{flexDirection:'row',gap:8},adjust:{flex:1,paddingVertical:11,borderRadius:10,borderWidth:1,alignItems:'center'},adjustInfo:{padding:10,borderRadius:10,gap:3},save:{marginTop:3,paddingVertical:13,borderRadius:11,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},saveText:{color:'#fff',fontWeight:'900'}});
