/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/co/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/co/client-summary`; params?: Router.UnknownInputParams; } | { pathname: `/co/close-account`; params?: Router.UnknownInputParams; } | { pathname: `/co/combined`; params?: Router.UnknownInputParams; } | { pathname: `/co/disbursement`; params?: Router.UnknownInputParams; } | { pathname: `/co/history`; params?: Router.UnknownInputParams; } | { pathname: `/co/loan-collection`; params?: Router.UnknownInputParams; } | { pathname: `/co/passkey`; params?: Router.UnknownInputParams; } | { pathname: `/co/register`; params?: Router.UnknownInputParams; } | { pathname: `/co/savings`; params?: Router.UnknownInputParams; } | { pathname: `/co/union-groups`; params?: Router.UnknownInputParams; } | { pathname: `/co/withdrawal`; params?: Router.UnknownInputParams; } | { pathname: `/client/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/co/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/co/client-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/co/close-account`; params?: Router.UnknownOutputParams; } | { pathname: `/co/combined`; params?: Router.UnknownOutputParams; } | { pathname: `/co/disbursement`; params?: Router.UnknownOutputParams; } | { pathname: `/co/history`; params?: Router.UnknownOutputParams; } | { pathname: `/co/loan-collection`; params?: Router.UnknownOutputParams; } | { pathname: `/co/passkey`; params?: Router.UnknownOutputParams; } | { pathname: `/co/register`; params?: Router.UnknownOutputParams; } | { pathname: `/co/savings`; params?: Router.UnknownOutputParams; } | { pathname: `/co/union-groups`; params?: Router.UnknownOutputParams; } | { pathname: `/co/withdrawal`; params?: Router.UnknownOutputParams; } | { pathname: `/client/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/co/analytics${`?${string}` | `#${string}` | ''}` | `/co/client-summary${`?${string}` | `#${string}` | ''}` | `/co/close-account${`?${string}` | `#${string}` | ''}` | `/co/combined${`?${string}` | `#${string}` | ''}` | `/co/disbursement${`?${string}` | `#${string}` | ''}` | `/co/history${`?${string}` | `#${string}` | ''}` | `/co/loan-collection${`?${string}` | `#${string}` | ''}` | `/co/passkey${`?${string}` | `#${string}` | ''}` | `/co/register${`?${string}` | `#${string}` | ''}` | `/co/savings${`?${string}` | `#${string}` | ''}` | `/co/union-groups${`?${string}` | `#${string}` | ''}` | `/co/withdrawal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/co/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/co/client-summary`; params?: Router.UnknownInputParams; } | { pathname: `/co/close-account`; params?: Router.UnknownInputParams; } | { pathname: `/co/combined`; params?: Router.UnknownInputParams; } | { pathname: `/co/disbursement`; params?: Router.UnknownInputParams; } | { pathname: `/co/history`; params?: Router.UnknownInputParams; } | { pathname: `/co/loan-collection`; params?: Router.UnknownInputParams; } | { pathname: `/co/passkey`; params?: Router.UnknownInputParams; } | { pathname: `/co/register`; params?: Router.UnknownInputParams; } | { pathname: `/co/savings`; params?: Router.UnknownInputParams; } | { pathname: `/co/union-groups`; params?: Router.UnknownInputParams; } | { pathname: `/co/withdrawal`; params?: Router.UnknownInputParams; } | `/client/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/client/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
